// Every line of on-screen text lives here, in two styles.
// "simple" is plain, easy English (the default). "story" is the sci-fi flavour.
// Players switch between them in Settings > Text style.
// To change any wording, edit it here. {n}, {nn}, {w}, {s}, {msg} are filled in by the game.

export const TEXT = {
  simple: {
    'loader.engage': 'Click or press any key to start',
    'loader.hint': 'Move your mouse to swirl the colours',
    'loader.cold': 'Loading',
    'boot.1': 'Starting the graphics engine',
    'boot.2': 'Drawing the sky, sun and floor',
    'boot.3': 'Adding background layers',
    'boot.4': 'Building the ships',
    'boot.5': 'Getting explosions ready',
    'boot.6': 'Preparing shaders',
    'boot.7': 'Setting up music and sound',
    'boot.8': 'Loading saved scores',
    'boot.9': 'Almost ready',
    'boot.ready': 'Ready in {s}s',
    'boot.failed': 'Something went wrong: {msg}',

    'menu.play': 'Play',
    'menu.howto': 'How to Play',
    'menu.scores': 'High Scores',
    'menu.settings': 'Settings',
    'menu.credits': 'Credits',
    'menu.best': 'Best score',
    'menu.version': 'Version',
    'menu.by': 'a game by {name}',
    'ticker.1': 'The sun is stuck on the horizon and enemy drones are coming down.',
    'ticker.2': 'Shoot them down and beat the boss at the end of every level.',
    'ticker.3': 'Pick up power-ups for more firepower, a shield or extra health.',
    'ticker.4': 'Tip: dash through an enemy to destroy it.',
    'ticker.5': 'Tip: kill enemies quickly to raise your score multiplier.',

    'howto.title': 'How to Play',
    'howto.move': 'move',
    'howto.fire': 'shoot (hold down)',
    'howto.dash': 'dash, a quick dodge where you can\'t be hit',
    'howto.emp': 'bomb, clears bullets and hurts every enemy',
    'howto.pause': 'pause',
    'howto.fullscreen': 'full screen',
    'howto.od': 'overdrive, slows time and powers up your shots',
    'howto.pad': 'stick to move, A shoot, B dash, X bomb, Y overdrive',
    'howto.enemies': 'ENEMIES',
    'howto.mote': 'Small drone. Comes in groups and dies fast.',
    'howto.lancer': 'Stays back and fires short bursts at you.',
    'howto.hornet': 'Locks on and flies at you. Dodge it or dash through it.',
    'howto.warden': 'Big and tough. Fires rings of bullets, so look for the gap.',
    'howto.splitter': 'Breaks into small fast drones when destroyed.',
    'howto.boss': 'The boss at the end of each level. Gets angrier as it takes damage.',
    'howto.scoring': 'SCORING',
    'howto.scoringText': 'Kill enemies quickly to build your multiplier, up to x8. Getting hit resets it. Finish a wave without getting hit for a bonus.',
    'common.back': 'Back',

    'scores.title': 'High Scores',
    'scores.level': 'Level {n}',

    'settings.title': 'Settings',
    'settings.music': 'Music',
    'settings.sfx': 'Sound effects',
    'settings.dim': 'Background in game',
    'settings.dimLow': 'Dim (easiest to see)',
    'settings.dimMid': 'Medium',
    'settings.dimFull': 'Full brightness',
    'settings.graphics': 'Graphics',
    'settings.high': 'High (best look)',
    'settings.low': 'Low (older laptops)',
    'settings.shake': 'Screen shake',
    'settings.fps': 'Show FPS',
    'settings.textStyle': 'Text style',
    'settings.simple': 'Simple English',
    'settings.story': 'Sci-fi story',
    'settings.textSize': 'Text size',
    'settings.normal': 'Normal',
    'settings.large': 'Large',
    'settings.xlarge': 'Extra large',
    'settings.reset': 'Reset high scores',
    'settings.resetConfirm': 'Click again to confirm',
    'settings.resetDone': 'High scores reset',
    'settings.difficulty': 'Difficulty',
    'settings.easy': 'Easy',
    'settings.hard': 'Hard',
    'settings.hints': 'Tutorial tips',

    'credits.title': 'Credits',
    'credits.made': 'Made by',
    'credits.render': 'Graphics',
    'credits.renderText': 'three.js and custom shaders',
    'credits.music': 'Music',
    'credits.musicText': 'Made with code using the Web Audio API. No audio files.',
    'credits.type': 'Fonts',
    'credits.for': 'Made for',
    'credits.forText': 'JSS University game dev showcase',

    'hud.score': 'SCORE',
    'hud.level': 'LEVEL',
    'hud.best': 'BEST',
    'hud.hull': 'HEALTH',
    'hud.shield': 'SHIELD',
    'hud.dash': 'DASH',
    'hud.emp': 'BOMB',
    'hud.boss': 'BOSS',
    'hud.chain': 'COMBO {n}',
    'hud.od': 'OVERDRIVE',
    'hud.odReady': 'OVERDRIVE READY · R',
    'demo.tag': 'Press any key to play',

    'pause.title': 'Paused',
    'pause.resume': 'Resume',
    'pause.restart': 'Restart',
    'pause.quit': 'Main Menu',

    'go.lost': 'Game Over',
    'go.record': 'New High Score!',
    'go.final': 'FINAL SCORE',
    'go.best': 'BEST {n}',
    'go.personal': 'YOUR BEST SCORE',
    'go.level': 'LEVEL',
    'go.kills': 'KILLS',
    'go.accuracy': 'ACCURACY',
    'go.chain': 'BEST COMBO',
    'go.time': 'TIME',
    'go.bosses': 'BOSSES BEATEN',
    'go.entry': 'You made the high score list! Type your initials',
    'go.save': 'Save',
    'go.again': 'Play Again',
    'go.menu': 'Main Menu',
    'go.medals': 'MEDALS',
    'medal.none': 'No medals this time. Try again!',
    'medal.sharp': 'Sharpshooter',
    'medal.combo': 'Combo Master',
    'medal.boss': 'Boss Breaker',
    'medal.untouch': 'Untouchable',
    'medal.survivor': 'Survivor',
    'medal.ace': 'Ace Pilot',
    'medal.od': 'Time Bender',

    'b.sector': 'LEVEL {n}',
    'b.wave': 'LEVEL {n} · WAVE {w}',
    'wave.1': 'Enemies incoming',
    'wave.2': 'Here comes more',
    'wave.3': 'They are getting stronger',
    'wave.4': 'Last wave before the boss',
    'b.clear': 'WAVE CLEAR',
    'b.perfect': 'PERFECT, NO DAMAGE',
    'b.warning': 'WARNING',
    'b.bossIncoming': 'Boss incoming',
    'b.breach': 'BOSS DAMAGED',
    'b.armour': 'Its armour is breaking',
    'b.core': 'The core is open, keep shooting',
    'b.failing': 'BOSS IS GOING DOWN',
    'b.failingSub': 'Stay clear of the blast',
    'b.sectorClear': 'LEVEL COMPLETE',
    'b.sectorClearSub': '+{n} · health restored',
    'b.warp': 'WARP JUMP',
    'b.warpSub': 'Hold on tight',
    'b.od': 'OVERDRIVE',
    'b.odSub': 'Time slowed · shots pierce',

    'pickup.spread': 'SPREAD SHOT',
    'pickup.rapid': 'RAPID FIRE',
    'pickup.shield': 'SHIELD ON',
    'pickup.repair': 'HEALTH +30',
    'pickup.emp': 'BOMB +1',
    'pickup.missile': 'HOMING MISSILES',
    'toast.ram': 'DASH KILL +250',
    'toast.quality': 'GRAPHICS LOWERED FOR SMOOTH PLAY',
    'toast.odReady': 'OVERDRIVE READY · PRESS R',

    'hint.move': 'Move your mouse to fly',
    'hint.fire': 'Hold left click to shoot',
    'hint.dash': "Press Shift to dash. You can't be hit while dashing",
    'hint.bomb': 'Press E for a bomb when it gets busy',
    'hint.od': 'Kill enemies to fill Overdrive, then press R',
  },

  story: {
    'loader.engage': 'Click or press any key to engage',
    'loader.hint': 'move the cursor, stir the haze',
    'loader.cold': 'cold start',
    'boot.1': 'spinning up webgl2 renderer',
    'boot.2': 'painting sky, sun + grid shaders',
    'boot.3': 'laying parallax layers',
    'boot.4': 'forging hulls: kestrel-7 + hostiles',
    'boot.5': 'allocating particle + shockwave pools',
    'boot.6': 'compiling shader programs',
    'boot.7': 'patching synth voices + reverb',
    'boot.8': 'reading pilot records',
    'boot.9': 'warming up the render loop',
    'boot.ready': 'ready in {s}s',
    'boot.failed': 'boot failed: {msg}',

    'menu.play': 'Launch Sortie',
    'menu.howto': 'Flight Manual',
    'menu.scores': 'Hall of Embers',
    'menu.best': 'Personal best',
    'menu.version': 'Build',
    'menu.by': 'a {name} production',
    'ticker.1': '2189. The sun over the Neon Basin has been setting for eleven years.',
    'ticker.2': 'HELIOS engines in low orbit are holding it at the horizon.',
    'ticker.3': 'Every dusk the drones come down with the light.',
    'ticker.4': 'KESTREL-7 is the last interceptor still rated for the glare.',
    'ticker.5': 'Fly the corridor. Break the engines. Let the night in.',

    'howto.title': 'Flight Manual',
    'howto.move': 'steer',
    'howto.fire': 'fire (hold)',
    'howto.dash': 'barrel-roll dash, brief invulnerability',
    'howto.emp': 'EMP: wipes bullets, hurts everything',
    'howto.fullscreen': 'fullscreen',
    'howto.od': 'overdrive: bullet time, piercing rounds',
    'howto.pad': 'stick, A fire, B dash, X EMP, Y overdrive, Start pause',
    'howto.enemies': 'CONTACTS',
    'howto.mote': 'Swarm drone. Flies in formation, dies fast.',
    'howto.lancer': 'Holds range and fires aimed bursts.',
    'howto.hornet': 'Locks on and rams. Dash through it.',
    'howto.warden': 'Heavy. Fires expanding rings. Find the gap.',
    'howto.splitter': 'Shatters into a swarm when it breaks.',
    'howto.boss': 'Waits at the end of every sector. Three phases.',
    'howto.scoringText': 'Kills inside the chain window build your multiplier up to x8. Taking a hit resets it. Clearing a wave without damage pays a bonus.',

    'scores.title': 'Hall of Embers',
    'scores.level': 'Sector {nn}',

    'credits.made': 'Design, code, audio',
    'credits.render': 'Rendering',
    'credits.renderText': 'three.js (MIT) + custom GLSL',
    'credits.music': 'Soundtrack',
    'credits.musicText': 'Generated live by the in-game synth. No audio files.',
    'credits.type': 'Type',
    'credits.for': 'Built for',

    'hud.level': 'SECTOR',
    'hud.hull': 'HULL',
    'hud.emp': 'EMP',
    'hud.boss': 'HELIOS ENGINE',
    'hud.chain': 'CHAIN {n}',
    'demo.tag': 'Press any key to take control',

    'pause.title': 'Holding Pattern',
    'pause.restart': 'Restart Sortie',
    'pause.quit': 'Abort to Menu',

    'go.lost': 'Signal Lost',
    'go.record': 'New Record',
    'go.personal': 'PERSONAL BEST',
    'go.level': 'SECTOR',
    'go.chain': 'MAX CHAIN',
    'go.bosses': 'BOSSES',
    'go.entry': 'Leaderboard spot. Enter your callsign',
    'go.save': 'Log it',
    'go.again': 'Fly Again',
    'go.medals': 'CITATIONS',

    'b.sector': 'SECTOR {nn}',
    'b.wave': 'SECTOR {nn} // WAVE {w}',
    'wave.1': 'Hostiles inbound',
    'wave.2': 'Second push',
    'wave.3': 'They are adapting',
    'wave.4': 'Hold the corridor',
    'b.perfect': 'NO DAMAGE TAKEN',
    'b.bossIncoming': 'Helios Engine approaching',
    'b.breach': 'CORE BREACH',
    'b.armour': 'Armour cracking',
    'b.core': 'Core exposed',
    'b.failing': 'ENGINE FAILING',
    'b.failingSub': 'Get clear',
    'b.sectorClear': 'SECTOR CLEARED',
    'b.sectorClearSub': '+{n} // hull patched',
    'b.warp': 'JUMP DRIVE',
    'b.warpSub': 'Next sector',
    'b.odSub': 'Bullet time // piercing rounds',

    'pickup.spread': 'SPREAD CANNON',
    'pickup.shield': 'SHIELD CHARGED',
    'pickup.repair': 'HULL REPAIRED',
    'pickup.emp': 'EMP +1',
    'pickup.missile': 'SEEKER SWARM',
    'toast.ram': 'RAM KILL +250',
  },
};

let style = 'simple';

export function setTextStyle(name) {
  style = TEXT[name] ? name : 'simple';
  applyText();
}

// Look up a line. Falls back to the simple style, so "story" only needs the
// lines that actually differ.
export function t(key, vars) {
  let s = TEXT[style][key] ?? TEXT.simple[key] ?? key;
  if (vars) s = s.replace(/\{(\w+)\}/g, (_, k) => (vars[k] ?? ''));
  return s;
}

export function applyText(root = document) {
  root.querySelectorAll('[data-t]').forEach((el) => {
    el.textContent = t(el.dataset.t);
  });
}
